name: GitHub Actions Demo

on:
  push:
    branches:
      - main  # Specify the branch where this workflow should trigger

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step checks out your repository's code

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: adelromay/git_actions:latest

  docker-deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Run Docker container
        run: |
          sudo docker run -d -p 4000:80 adelromay/git_actions:latest  # Replace with your Docker image name

      - name: Check running containers
        run: |
          sudo docker ps
